### ISSUE TITLE
The GIF API Key seems to be out of date and returns undefined object.

### ISSUE THREAD

**Issue by zahidirfan** [hswolff/youtube#5]
https://github.com/hswolff/youtube/blob/16b0c141c042305831ed645ca667578ef7fa62ab/videos/react-demos/src/demo/async-hooks.js#L12

**Comment by hswolff** [comment]
Yep, that's on purpose! 

Make a developer account on Giphy and put in your own api key!

**Comment by zahidirfan** [comment]
Ok in that case it should also be either mentioned that the API Key needs to be defined in .env file which would implicitly mean to get the API Key.

**Comment by hswolff** [comment]
I'd love a PR to do that!
